//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giaodiencuoiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailInvoice
    {
        public int Id { get; set; }
        public Nullable<int> IdInvoice { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
