//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giaodiencuoiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.DetailInvoices = new HashSet<DetailInvoice>();
        }
    
        public int IdProduct { get; set; }
        public string Title { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Sold { get; set; }
        public Nullable<int> IdProductType { get; set; }
        public Nullable<float> Price { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailInvoice> DetailInvoices { get; set; }
    }
}
